Clean code otherdetails
elagarrigue/AyDS22-AK-NewYork3 pull request #2
Opened 2022-04-25 21:59 UTC by gonzarl

Refactor inicial de clean code sobre las clases OtherInfoWIndow y Database

2022-04-26 18:27 UTC, elagarrigue requested changes

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/DataBase.kt
> +        return if (artistInfoItems.isEmpty()) null else artistInfoItems[0]
Se puede simplificar
```suggestion
        return artistInfoItems.firstOrNull()
```

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private lateinit var ARTIST_NAME: String
los nombres de las propiedades van siempre en camelCase

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private lateinit var ARTIST_NAME: String
los nombres de las propiedades van siempre en camelCase

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        setContentView(R.layout.activity_other_info)
No corresponde al nivel de abstracción. El setContentView debería ser lo primero que se ejecute. Comparar con HomeView.

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        }.start()
Distento nivel de abstracción. Si disparamos un thread, que sólo llame a una función.

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        prepareOtherInfoView()
distintos niveles de abstracción

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        infoDataBase?.let { artistInfoWasInDataBase = true }
Cuidado con esta propiedad `artistInfoWasInDataBase`. A este nivel no está mal, pero se va a eliminar cuando implementen el patrón repository.

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        if (artistInfoWasInDataBase) "[*]$infoDataBase" else null
Definir una constante para `[*]`

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val artistInfoFromService = abstractNYT!!.asString.replace("\\n", "\n")
No es buena práctica usar `!!`. Si `abstractNYT` es null, no remplazar nada, es más seguro.

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        }
Diferente nivel de abstracción

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        findViewById<View>(R.id.openUrlButton).setOnClickListener {
Hace demasiadas cosas. Mejor obtener la referencia al botón y guardarla en una propiedad (idem HomeView)

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            this.startActivity(intent)
Diferente nivel de abstracción, mover a una subfunción

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        Picasso.get().load(logoNYT).into(findViewById<View>(R.id.imageView) as ImageView)
definir una propiedad para la view

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val nytInfoPane: TextView = findViewById(R.id.NYTInfoPane)
Propiedad para la vista. Los id deben estar en camelCase también.

2022-04-26 18:27 UTC, elagarrigue commented on app/src/main/res/layout/activity_other_info.xml
> +            android:id="@+id/NYTInfoPane"
camelCase

2022-04-27 12:15 UTC, AgustinGD commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        if (abstractNYT == null) EMPTY_ABSTRACT else null
Esto no se puede hacer con ?.let
Lo que intentamos hacer aca es que si el abstract es nulo devuelva el EMPTY_ABSTRACT, no lo contrario

2022-04-27 12:23 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        if (abstractNYT == null) EMPTY_ABSTRACT else null
correcto, lo vi al revés

2022-04-27 20:18 UTC, elagarrigue requested changes

2022-04-27 20:18 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        artistName = intent.getStringExtra(ARTIST_NAME_EXTRA)!!
No es el mismo nivel de abstracción, mover a sub fun

2022-04-27 20:18 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        artistName = intent.getStringExtra(ARTIST_NAME_EXTRA)!!
Evitar el !!. Mejor vacío por defecto `?: ""`.

2022-04-27 20:18 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        saveInDataBase(artistInfo)
Side effect, debería estar en el algoritmo de Repository

2022-04-27 20:18 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        val nytimesAPI = createRetrofit()
No debería crearse cada vez, y es otra responsibilidad. Crear una propiedad, como con DB.

2022-04-28 11:41 UTC, elagarrigue requested changes

2022-04-28 11:41 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        nytInfoPane = findViewById(R.id.nytInfoPane)
Distintos niveles de abstracción, indica que hace al menos 3 cosas:
- Inicializar propiedad de estado a través de un extra del intent
- Inicializar las dependencias de fuente de datos 
- Inicializar vistas
Separar en subfunciones

2022-04-28 11:41 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                updateURLButton()
esto quedó en medio del algoritmo de repository, es lógica de vista no de data. Termina siendo un side effect. Mover afuera.

2022-04-28 21:14 UTC, elagarrigue commented on app/src/main/java/ayds/newyork/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +                updateURLButton()
exacto, es responsabilidad de vista. Cuando creen el repository en la etapa siguiente van a poder hacerlo de una.

2022-04-29 14:26 UTC, merged